# Project: 專案11
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 4.o
LINKOBJ  = 4.o
LIBS     = -L"D:/dev-c++/DevCppPortable/MinGW64/lib" -L"D:/dev-c++/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/dev-c++/DevCppPortable/MinGW64/include" -I"D:/dev-c++/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/dev-c++/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/dev-c++/DevCppPortable/MinGW64/include" -I"D:/dev-c++/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/dev-c++/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/dev-c++/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "第四題.dev - 捷徑.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

4.o: 4.c
	$(CC) -c 4.c -o 4.o $(CFLAGS)
